#!/system/bin/sh
# PocketNVR Cloudflare Tunnel one-time setup (Design B — deploy/cloudflare/).
# Runs ON THE PHONE as root (adb shell su / Termux). Provisions a named
# tunnel "pocketnvr", routes <hostname> to it, writes
# /data/nvr/cloudflare/tunnel.yml, and hands the daemon to nvrctl.
# The edge-side auth (Cloudflare Access app + email policy) is configured
# in the Zero Trust dashboard — see deploy/cloudflare/README.md.
#
# Usage: sh /data/nvr/cloudflare/setup.sh <hostname> [origin]
#   e.g.  sh /data/nvr/cloudflare/setup.sh nvr.example.com
#   origin defaults to http://127.0.0.1:8099 (nvrd api.bind loopback).
#
# Needs: cloudflared installed at /data/nvr/bin/cloudflared (deploy.sh
# pushes it after scripts/fetch-cloudflared.sh) and a domain whose DNS
# lives on your Cloudflare account. `tunnel login` prints a URL — open it
# in any browser, pick your zone, and this script continues on its own.

set -e
BASE=/data/nvr
CF=$BASE/cloudflare
BIN=$BASE/bin
HOSTNAME_ARG="${1:-}"
ORIGIN="${2:-http://127.0.0.1:8099}"
# Pin everything cloudflared reads/writes under $CF: root's HOME is
# unstable under su, so default ~/.cloudflared paths are a trap.
# TUNNEL_ORIGIN_CERT is where login writes and every command reads.
HOME=$CF
TUNNEL_ORIGIN_CERT=$CF/cert.pem
export HOME TUNNEL_ORIGIN_CERT

if [ -z "$HOSTNAME_ARG" ]; then
	echo "usage: sh $0 <hostname> [origin]   e.g. sh $0 nvr.example.com" >&2
	exit 1
fi
[ -x "$BIN/cloudflared" ] || { echo "missing $BIN/cloudflared — run scripts/fetch-cloudflared.sh + scripts/deploy.sh" >&2; exit 1; }
command -v nvrctl >/dev/null 2>&1 || PATH=$BIN:$PATH

mkdir -p "$CF"
chmod 700 "$CF"

echo "== cloudflared $($BIN/cloudflared --version | awk '{print $3}')"

if [ ! -f "$CF/cert.pem" ]; then
	echo "== login: open the URL below in ANY browser, authorize, pick the zone for '$HOSTNAME_ARG'"
	echo "   (if it stalls or errors: easier path is the dashboard token —"
	echo "    deploy/cloudflare/README.md Method A / scripts/cloudflare-token.sh —"
	echo "    or run 'cloudflared tunnel login' on the Mac and"
	echo "    adb push ~/.cloudflared/cert.pem $CF/cert.pem, then rerun this)"
	"$BIN/cloudflared" tunnel login
fi
[ -f "$CF/cert.pem" ] || {
	echo "login did not produce cert.pem. Rescue options:" >&2
	echo "  a) run on the Mac:  third_party/cloudflared/current/darwin_arm64/cloudflared tunnel login" >&2
	echo "     then:            adb push ~/.cloudflared/cert.pem $CF/cert.pem" >&2
	echo "  b) skip login entirely (Method A): Zero Trust dashboard -> create a" >&2
	echo "     tunnel, then:    scripts/cloudflare-token.sh <token>" >&2
	exit 1
}

if "$BIN/cloudflared" tunnel list -o json --name pocketnvr 2>/dev/null | grep -q '"name":"pocketnvr"'; then
	echo "== tunnel 'pocketnvr' already exists — refreshing credentials file"
	"$BIN/cloudflared" tunnel token --cred-file "$CF/pocketnvr.json" pocketnvr
else
	echo "== creating tunnel 'pocketnvr'"
	"$BIN/cloudflared" tunnel create pocketnvr
	# create writes under $HOME/.cloudflared — keep secrets at a known path
	mv "$CF/.cloudflared/pocketnvr.json" "$CF/pocketnvr.json"
fi
[ -f "$CF/pocketnvr.json" ] || { echo "credentials file missing — rerun" >&2; exit 1; }
chmod 600 "$CF/cert.pem" "$CF/pocketnvr.json"

echo "== routing DNS: $HOSTNAME_ARG -> pocketnvr"
if [ -n "${FORCE:-}" ]; then
	"$BIN/cloudflared" tunnel route dns -f pocketnvr "$HOSTNAME_ARG"
else
	"$BIN/cloudflared" tunnel route dns pocketnvr "$HOSTNAME_ARG" || {
		echo "route failed (existing record?). Rerun with FORCE=1 to overwrite it." >&2
		exit 1
	}
fi

cat > "$CF/tunnel.yml" <<EOF
# PocketNVR ingress (Design B). Generated by setup.sh — edit the service
# URL here if api.bind changes. Auth is enforced at Cloudflare's edge
# (Cloudflare Access), not here.
tunnel: pocketnvr
credentials-file: $CF/pocketnvr.json
metrics: 127.0.0.1:0
ingress:
  - hostname: $HOSTNAME_ARG
    service: $ORIGIN
  - service: http_status:404
EOF
chmod 600 "$CF/tunnel.yml"

echo "== starting supervised tunnel (nvrctl keeps it alive from here on)"
nvrctl restart tunnel || nvrctl start tunnel
sleep 2
nvrctl status tunnel

cat <<NEXT

== tunnel up. Finish Layer 1 in the Zero Trust dashboard:
   1. Access > Applications > Add > Self-hosted  ->  $HOSTNAME_ARG
   2. Policy: Allow / Include / Emails (or Login with Google) — the people you approve
   3. Login settings: session duration (e.g. 24h) + return 401 on expired sessions
      (so SSE/HLS fail into the PWA login gate instead of getting HTML)
   4. config.yaml: notifications.base_url: https://$HOSTNAME_ARG   then SIGHUP nvrd
   Full walkthrough: deploy/cloudflare/README.md
NEXT
