// Package mediamtx renders the MediaMTX runtime config from the single
// config.yaml (FR-CFG-1), so camera/auth/retention settings are never
// duplicated. Targets MediaMTX v1.21.0 (vendored, see third_party/mediamtx).
package mediamtx

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"

	"pocketnvr/internal/config"
)

// Generate renders mediamtx.yml.
//
// Layout per FRS AD-1/AD-2: each camera exposes <id> (main) and <id>_sub
// (sub) restreams sourced from the real cameras. Recording is stream-copy
// segmented fMP4 (FR-MED-2; MediaMTX v1.x only supports fmp4 — still no
// re-encode, files are .mp4) with age-based deletion (FR-MED-3); event_only
// mode disables continuous recording (FR-MED-6).
//
// Auth (FR-MED-5): a viewer account (password from secrets key
// mediamtx_viewer_pass) may read from anywhere; localhost gets
// passwordless read+publish so the detector and nvrctl never need the
// secret. Everything else is rejected.
// viewerPass comes from secrets.yaml key `mediamtx_viewer_pass`.
// recordOverride lets the free-space guard (FR-SUP-8) force recording off
// (false) or on (nil = follow config recording.mode).
func Generate(cfg *config.Config, viewerPass string, recordOverride *bool) ([]byte, error) {
	type cam struct {
		ID         string
		SourceMain string
		SourceSub  string
	}
	cams := make([]cam, 0, len(cfg.Cameras))
	for _, c := range cfg.Cameras {
		if !c.IsEnabled() {
			continue
		}
		cams = append(cams, cam{ID: c.ID, SourceMain: c.SourceMain, SourceSub: c.SourceSub})
	}
	if len(cams) == 0 {
		return nil, fmt.Errorf("no enabled cameras: refusing to generate empty mediamtx config")
	}
	record := cfg.Recording.Mode == "continuous"
	if recordOverride != nil {
		record = *recordOverride
	}
	deleteAfter := time.Duration(cfg.Recording.RetentionDays) * 24 * time.Hour
	segDur := time.Duration(cfg.Recording.SegmentSeconds) * time.Second
	if deleteAfter <= segDur {
		return nil, fmt.Errorf("recording.retention_days must exceed segment_seconds")
	}

	tpl := template.Must(template.New("m").Parse(`# Generated by pocketnvr (internal/mediamtx). DO NOT EDIT.
# Source of truth: config.yaml — regenerate via ` + "`nvrd mediamtx-config`" + `.
logLevel: {{.LogLevel}}
api: no
metrics: no
playback: yes
playbackAddress: {{.PlaybackAddress}}
rtsp: yes
rtspAddress: {{.RTSPAddress}}
rtmp: no
srt: no
webrtc: yes
webrtcAddress: {{.WebRTCAddress}}
hls: yes
hlsAddress: {{.HLSAddress}}

authInternalUsers:
  - user: {{.AuthUser}}
    pass: {{.ViewerPass}}
    permissions:
      - action: read
  - user: any
    ips: [127.0.0.1, '::1']
    permissions:
      - action: publish
      - action: read

pathDefaults:
  sourceOnDemand: no
  # Tapo/Dahua cameras lose packets over UDP RTSP — force TCP (FLAG-8)
  sourceProtocol: tcp
  record: {{.Record}}
  recordPath: {{.BasePath}}/recordings/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordSegmentDuration: {{.SegmentDuration}}
  recordDeleteAfter: {{.DeleteAfter}}

paths:
{{- range .Cameras}}
  {{.ID}}:
    source: {{.SourceMain}}
  {{.ID}}_sub:
    source: {{.SourceSub}}
{{- end}}
`))

	var b bytes.Buffer
	err := tpl.Execute(&b, map[string]any{
		"LogLevel":        cfg.System.LogLevel,
		"RTSPAddress":     cfg.Media.RTSPAddress,
		"WebRTCAddress":   cfg.Media.WebRTCAddress,
		"HLSAddress":      cfg.Media.HLSAddress,
		"AuthUser":        cfg.Media.AuthUser,
		"ViewerPass":      viewerPass,
		"Record":          boolYN(record),
		"BasePath":        cfg.System.BasePath,
		"SegmentDuration": segDur.String(),
		"DeleteAfter":     deleteAfter.String(),
		"Cameras":         cams,
		"PlaybackAddress": cfg.Media.PlaybackAddress,
	})
	if err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

func boolYN(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

// LocalStreamURLs returns the restream URLs the detector and UI use.
func LocalStreamURLs(cfg *config.Config, camID string) (main, sub string) {
	host := "127.0.0.1"
	if strings.HasPrefix(cfg.Media.RTSPAddress, ":") {
		return "rtsp://" + host + cfg.Media.RTSPAddress + "/" + camID,
			"rtsp://" + host + cfg.Media.RTSPAddress + "/" + camID + "_sub"
	}
	return cfg.Media.RTSPAddress + "/" + camID, cfg.Media.RTSPAddress + "/" + camID + "_sub"
}
